### ISSUE TITLE
Some Games don't use ow-overlay.exe

### ISSUE THREAD

**Issue by Marshall-67** [SurgeGotTappedAgain/Window-Hijack#2]
Firstly thanks for the project it helped me understand hijacking overlays alot more.

I was using this for csgo/cs2 and i tried testing it on DBD/Squad and noticed that they don't appear to be using ow-overlay.exe even though the overwolf overlay works like normal. i even tried cs:source and that didnt use it either just csgo/cs2 

I tried looking for window flags in processhacker but i couldn't find the same flags that ow-overlay had

any idea? thanks

**Comment by SurgeGotTappedAgain** [comment]
yes, some games load the ow-overlay.dll into there process instead of "creating" a window. so just make sure you're game does not load the .dll

**Comment by Marshall-67** [comment]
> yes, some games load the ow-overlay.dll into there process instead of "creating" a window. so just make sure you're game does not load the .dll

Figured out you can actually just force the overlay.exe to be created on the game with cmd lol

**Comment by SurgeGotTappedAgain** [comment]
let me know how you did it and I’ll add it to my repo for people

**Comment by ZaweSec** [comment]
someone have found a method to use ow-overlay to other game?
